/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Miriam
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        juego1 = new javax.swing.JButton();
        mapa = new javax.swing.JButton();
        formulario = new javax.swing.JButton();
        juego = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        juego1.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        juego1.setForeground(new java.awt.Color(0, 153, 51));
        juego1.setText("Juego");
        juego1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juego1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mapa.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        mapa.setForeground(new java.awt.Color(255, 0, 51));
        mapa.setText("Donde Estoy");
        mapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapaActionPerformed(evt);
            }
        });
        getContentPane().add(mapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 150, 70));

        formulario.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        formulario.setForeground(new java.awt.Color(0, 0, 204));
        formulario.setText("Formulario");
        formulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formularioActionPerformed(evt);
            }
        });
        getContentPane().add(formulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 150, 70));

        juego.setFont(new java.awt.Font("Bodoni MT Black", 0, 24)); // NOI18N
        juego.setForeground(new java.awt.Color(0, 153, 51));
        juego.setText("Juego");
        juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoActionPerformed(evt);
            }
        });
        getContentPane().add(juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 150, 70));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miriam\\Documents\\NetBeansProjects\\Proyecto_Infantil\\src\\main\\java\\Imagen\\logo3.png")); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 270));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miriam\\Documents\\NetBeansProjects\\Proyecto_Infantil\\src\\main\\java\\Imagen\\inicio.jpg")); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 544, 353));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapaActionPerformed
        setVisible(false);
        new Mapa().setVisible(true);
    }//GEN-LAST:event_mapaActionPerformed

    private void formularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formularioActionPerformed
        setVisible(false);
        new Formulario().setVisible(true);
    }//GEN-LAST:event_formularioActionPerformed

    private void juego1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juego1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juego1ActionPerformed

    private void juegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoActionPerformed
        setVisible(false);
        new InicioJuego().setVisible(true);
    }//GEN-LAST:event_juegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton formulario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton juego;
    private javax.swing.JButton juego1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton mapa;
    // End of variables declaration//GEN-END:variables
}
