/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Miriam
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gato = new javax.swing.JButton();
        perro = new javax.swing.JButton();
        gallo = new javax.swing.JButton();
        burro = new javax.swing.JButton();
        cerdo = new javax.swing.JButton();
        vaca = new javax.swing.JButton();
        oveja = new javax.swing.JButton();
        leon = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        respuesta = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gato.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miriam\\Documents\\NetBeansProjects\\Proyecto_Infantil\\src\\main\\java\\Imagen\\gato.jpg")); // NOI18N
        gato.setActionCommand("gato");
        gato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gatoActionPerformed(evt);
            }
        });
        gato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gatoKeyReleased(evt);
            }
        });
        getContentPane().add(gato, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 130, 130));

        perro.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miriam\\Documents\\NetBeansProjects\\Proyecto_Infantil\\src\\main\\java\\Imagen\\perro.jpg")); // NOI18N
        perro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perroActionPerformed(evt);
            }
        });
        getContentPane().add(perro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 130));
        perro.getAccessibleContext().setAccessibleDescription("");

        gallo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miriam\\Documents\\NetBeansProjects\\Proyecto_Infantil\\src\\main\\java\\Imagen\\gallo.jpg")); // NOI18N
        gallo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galloActionPerformed(evt);
            }
        });
        getContentPane().add(gallo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 130));

        burro.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miriam\\Documents\\NetBeansProjects\\Proyecto_Infantil\\src\\main\\java\\Imagen\\burro.jpg")); // NOI18N
        burro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burroActionPerformed(evt);
            }
        });
        getContentPane().add(burro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, 130));

        cerdo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miriam\\Documents\\NetBeansProjects\\Proyecto_Infantil\\src\\main\\java\\Imagen\\cerdo.jpg")); // NOI18N
        cerdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerdoActionPerformed(evt);
            }
        });
        getContentPane().add(cerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 130, 130));

        vaca.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miriam\\Documents\\NetBeansProjects\\Proyecto_Infantil\\src\\main\\java\\Imagen\\vaca.jpg")); // NOI18N
        vaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacaActionPerformed(evt);
            }
        });
        getContentPane().add(vaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 130, 130));

        oveja.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miriam\\Documents\\NetBeansProjects\\Proyecto_Infantil\\src\\main\\java\\Imagen\\oveja.jpg")); // NOI18N
        oveja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovejaActionPerformed(evt);
            }
        });
        getContentPane().add(oveja, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 130, 130));

        leon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miriam\\Documents\\NetBeansProjects\\Proyecto_Infantil\\src\\main\\java\\Imagen\\leon.jpg")); // NOI18N
        leon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leonActionPerformed(evt);
            }
        });
        getContentPane().add(leon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 130, 130));

        inicio.setBackground(new java.awt.Color(255, 153, 255));
        inicio.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        inicio.setForeground(new java.awt.Color(255, 0, 0));
        inicio.setText("Inicio");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 80, 30));

        respuesta.setFont(new java.awt.Font("Bodoni MT Black", 0, 48)); // NOI18N
        respuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 270, 90));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Miriam\\Documents\\NetBeansProjects\\Proyecto_Infantil\\src\\main\\java\\Imagen\\juego.jpg")); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 676, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        setVisible(false);
        new Inicio().setVisible(true);
    }//GEN-LAST:event_inicioActionPerformed

    private void perroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perroActionPerformed
        respuesta.setText("PERRO");
    }//GEN-LAST:event_perroActionPerformed

    private void gatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gatoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_gatoKeyReleased

    private void gatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gatoActionPerformed
         respuesta.setText("GATO");
    }//GEN-LAST:event_gatoActionPerformed

    private void cerdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerdoActionPerformed
         respuesta.setText("CERDO");
    }//GEN-LAST:event_cerdoActionPerformed

    private void galloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galloActionPerformed
         respuesta.setText("GALLO");
    }//GEN-LAST:event_galloActionPerformed

    private void vacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacaActionPerformed
         respuesta.setText("VACA");
    }//GEN-LAST:event_vacaActionPerformed

    private void burroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burroActionPerformed
         respuesta.setText("BURRO");
    }//GEN-LAST:event_burroActionPerformed

    private void ovejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovejaActionPerformed
         respuesta.setText("OVEJA");
    }//GEN-LAST:event_ovejaActionPerformed

    private void leonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leonActionPerformed
          respuesta.setText("LEON");
    }//GEN-LAST:event_leonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton burro;
    private javax.swing.JButton cerdo;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton gallo;
    private javax.swing.JButton gato;
    private javax.swing.JButton inicio;
    private javax.swing.JButton leon;
    private javax.swing.JButton oveja;
    private javax.swing.JButton perro;
    private javax.swing.JLabel respuesta;
    private javax.swing.JButton vaca;
    // End of variables declaration//GEN-END:variables
}
